"""Модули работы с базой данных."""
from src.database.database import (
    init_db,
    get_connection,
    get_or_create_user,
    get_user_by_hash,
    create_user,
    create_scan,
    update_scan_status,
    get_scan,
    save_virustotal_result,
    get_cached_virustotal_result,
    save_llm_analysis,
    get_llm_analysis,
    save_file,
    get_file_by_scan,
    delete_file_record,
    get_scan_history_by_user_and_month,
    get_months_with_scans,
    get_scan_with_details,
    cleanup_old_data,
)

__all__ = [
    "init_db",
    "get_connection",
    "get_or_create_user",
    "get_user_by_hash",
    "create_user",
    "create_scan",
    "update_scan_status",
    "get_scan",
    "save_virustotal_result",
    "get_cached_virustotal_result",
    "save_llm_analysis",
    "get_llm_analysis",
    "save_file",
    "get_file_by_scan",
    "delete_file_record",
    "get_scan_history_by_user_and_month",
    "get_months_with_scans",
    "get_scan_with_details",
    "cleanup_old_data",
]
